---
driver:
  name: docker
  <%= "http_proxy: http://#{ENV['LOCALPROXY']}" if ENV['LOCALPROXY'] %>
  <%= "https_proxy: http://#{ENV['LOCALPROXY']}" if ENV['LOCALPROXY'] %>
driver_config:
  require_chef_omnibus: true

#provisioner:
#  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
- name: ubuntu-16.04
  run_list:
  - recipe[apt]
- name: ubuntu-14.04
  run_list:

suites:
- name: default
  run_list:
  - recipe[xylophone]
  attributes: {
    "nginx": {
      "upstream_repository": "http://nginx.org/packages/ubuntu"
    },
    "xylophone": {
    }
  }
